import pathlib
import argparse
from umap import UMAP
import pandas as pd

# Bert
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

# File / Dataset
from isca_archive.analyze.common.dataset import ISCAArchiveProcessedDataset
from isca_archive.analyze.common.bertopic_visualisation import (
    visualize_topics,
    visualize_documents,
    visualize_barchart,
    visualize_hierarchy,
    visualize_topics_over_time,
    visualize_document_datamap
)

import plotly.io as pio
pio.kaleido.scope.default_format = "svg"
colors: list[str] = [
    "rgba(150, 20, 30, .7)",
    "rgba(244, 213, 130, .7)",
    "rgba(91, 190, 243, .7)",
    "rgba(0, 100, 0, .7)",
    "rgba(150, 150, 150, .7)",
]


def add_subparsers(subparsers):
    parser = subparsers.add_parser("visualize_topics", help="Visualise the topic previously extracted using BERTopic")

    parser.add_argument(
        "-i", "--inject-labels", type=str, default=None, help="Inject the custom labels (and merge topics if necessary)"
    )
    parser.add_argument(
        "-c",
        "--custom-labels",
        action="store_true",
        help="Use the custom labels instead of the ones generated by BERTopic",
    )

    # Add arguments
    parser.add_argument("input_dataframe", help="the ISCA Archive processed dataframe file")
    parser.add_argument("model_dir", help="The output directory")
    parser.add_argument("output_dir", help="The output directory")

    parser.set_defaults(func=main)


def main(args: argparse.Namespace):
    # Load the dataset
    dataset = ISCAArchiveProcessedDataset(
        args.input_dataframe,
    )
    docs = dataset.df

    # Load model and add embedding model
    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
    topic_model = BERTopic.load(args.model_dir, embedding_model=embedding_model)
    # Generate Embeddings (FIXME: focus)
    docs = docs[~pd.isna(docs["author_area_id"])]
    embeddings = embedding_model.encode(docs["content"], show_progress_bar=True)
    umap_model = UMAP(n_neighbors=10, n_components=2, min_dist=0.0, metric="cosine",random_state=42).fit(embeddings)
    reduced_embeddings = umap_model.embedding_

    # # Generate the figures
    figure_dir = pathlib.Path(args.output_dir)
    figure_dir.mkdir(parents=True, exist_ok=True)
    # fig = visualize_barchart(topic_model, custom_labels=args.custom_labels, width=500, top_n_topics=-1, n_words=-1)
    # fig.write_html(figure_dir / "topics_decomposition.html")

    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "topics_decomposition.svg", engine="kaleido")
    # fig.write_image(figure_dir / "topics_decomposition.pdf", engine="kaleido")

    # fig = visualize_topics(topic_model, custom_labels=args.custom_labels, width=600, height=600)
    # fig.write_html(figure_dir / "topics_map.html", include_plotlyjs=True)
    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})

    # fig.update_layout(
    #     font=dict(
    #         size=22,  # Set the font size here
    #     ))
    # fig.write_image(figure_dir / "topics_map.svg", engine="kaleido")
    # fig.write_image(figure_dir / "topics_map.pdf", engine="kaleido")

    # fig = topic_model.visualize_heatmap(custom_labels=args.custom_labels, n_clusters=4)
    # fig.write_html(figure_dir / "topics_similarity_heatmap.html", include_plotlyjs=True)
    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "topics_similarity_heatmap.svg", engine="kaleido")
    # fig.write_image(figure_dir / "topics_similarity_heatmap.pdf", engine="kaleido")

    # fig = visualize_documents(
    #     topic_model,
    #     docs["content"],
    #     embeddings=embeddings,
    #     reduced_embeddings=reduced_embeddings,
    #     hide_document_hover=False,
    #     hide_annotations=False,
    #     custom_labels=args.custom_labels,
    # )
    # fig.write_html(figure_dir / "document_embeddings.html")
    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "document_embeddings.svg", engine="kaleido")
    # fig.write_image(figure_dir / "document_embeddings.pdf", engine="kaleido")

    if args.inject_labels is not None:
        fig = visualize_documents(
            topic_model,
            docs["content"],
            embeddings=embeddings,
            reduced_embeddings=reduced_embeddings,
            hide_document_hover=False,
            hide_annotations=False,
            custom_labels=args.custom_labels,
            topic_column="topic" if args.inject_labels is None else "label",
            topic_association_df=pd.read_csv(args.inject_labels, sep="\t"),
            colors=colors,
            show_legend=False
        )
        fig.write_html(figure_dir / "document_embeddings_by_cluster.html")

        fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
        fig.update_layout(
            font=dict(
                size=22,  # Set the font size here
            ))
        fig.write_image(figure_dir / "document_embeddings_by_cluster.svg", engine="kaleido")
        fig.write_image(figure_dir / "document_embeddings_by_cluster.pdf", engine="kaleido")

    # df_area = docs[["BERTopic", "author_area_id"]].rename(columns={"BERTopic": "topic"}).drop_duplicates()
    # fig = visualize_documents(
    #     topic_model,
    #     docs["content"],
    #     embeddings=embeddings,
    #     reduced_embeddings=reduced_embeddings,
    #     hide_document_hover=True,
    #     hide_annotations=True,
    #     custom_labels=args.custom_labels,
    #     topic_column="author_area_id",
    #     topic_association_df=df_area
    # )
    # fig.write_html(figure_dir / "document_embeddings_by_isca_area.html")
    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "document_embeddings_by_isca_area.svg", engine="kaleido")
    # fig.write_image(figure_dir / "document_embeddings_by_isca_area.pdf", engine="kaleido")

    # # with the reduced embeddings
    # fig = visualize_document_datamap(
    #     topic_model,
    #     docs["content"],
    #     embeddings=embeddings,
    #     label_wrap_width=12,
    #     label_over_points=True,
    #     dynamic_label_size=True,
    #     max_font_size=36,
    #     min_font_size=4,
    #     min_font_weight=100,
    #     max_font_weight=1000,
    #     font_family="Roboto Condensed",
    # )
    # fig.savefig(figure_dir / "document_data_map.svg", bbox_inches="tight")
    # fig.savefig(figure_dir / "document_data_map.pdf", bbox_inches="tight")

    # # Distribution
    # topic_distr, _ = topic_model.approximate_distribution(docs["content"])
    # fig = topic_model.visualize_distribution(topic_distr[1], custom_labels=args.custom_labels)
    # fig.write_html(figure_dir / "distribution_topics.html")
    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "distribution_topics.svg", engine="kaleido")
    # fig.write_image(figure_dir / "distribution_topics.pdf", engine="kaleido")

    # # Hierarchical topic visualisation
    # hierarchical_topics = topic_model.hierarchical_topics(docs["content"], False,)
    # hierarchical_topics.to_csv(figure_dir/"hierarchical_topics.tsv", sep="\t")
    # fig = visualize_hierarchy(topic_model, hierarchical_topics=hierarchical_topics, custom_labels=args.custom_labels)
    # fig.write_html(figure_dir / "hierarchical_topics.html")

    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "hierarchical_topics.svg", engine="kaleido")
    # fig.write_image(figure_dir / "hierarchical_topics.pdf", engine="kaleido")

    # # Evolution over time
    # timestamps = docs.year
    # topics_over_time = topic_model.topics_over_time(docs["content"], timestamps)
    # fig = visualize_topics_over_time(
    #     topic_model, topics_over_time, custom_labels=args.custom_labels, normalize_frequency=True
    # )
    # fig.write_html(figure_dir / "topics_over_time.html")

    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "topics_over_time.svg", engine="kaleido")
    # fig.write_image(figure_dir / "topics_over_time.pdf", engine="kaleido")

    # # Evolution over time
    # fig = topic_model.visualize_term_rank(log_scale=True, custom_labels=args.custom_labels)
    # fig.write_html(figure_dir / "terms_rank_across_topics.html")

    # fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    # fig.write_image(figure_dir / "terms_rank_across_topics.svg", engine="kaleido")
    # fig.write_image(figure_dir / "terms_rank_across_topics.pdf", engine="kaleido")
